name: CI/CD Pipeline 
 
on: 
  push: 
    branches: 
      - main
      jobs: 
build-deploy: 
runs-on: ubuntu-latest 
steps: - name: Checkout 
uses: actions/checkout@v3 - name: Build Docker image 
run: docker build -t flaskapp . - name: Run Docker Compose 
run: docker-compose up -d 
